set search_path to vocabulary, dcc_pedsnet;

select * from concept where concept_id = 4298431;

--serum wbc
select concept_id, concept_code, concept_name, vocabulary_id,
	case when vocabulary_id = 'LOINC' then 'LC'
	end pcornet_vocabulary_id
from concept
where (lower(concept_name) like '%leukocyte%' or lower(concept_name) like '%white blood cell%')
	and (lower(concept_name) like '%serum%' or lower(concept_name) like '%plasma%' or lower(concept_name) like '%blood%')
	and vocabulary_id in ('LOINC')
	and lower(concept_name) not like '%morph%'
	and lower(concept_name) not like '%plasma%'
	and lower(concept_name) not like '%mono%'
	and lower(concept_name) not like '%blast%'
	and lower(concept_name) not like '%myelo%'
	and lower(concept_name) not like '%esterase%'
	and lower(concept_name) not like '%lympho%'
	and lower(concept_name) not like '%segmented%'
	and lower(concept_name) not like '%band%'
	and lower(concept_name) not like '%neutrophil%'
	and lower(concept_name) not like '%ratio%'
	and lower(concept_name) not like '%granulo%'
	and lower(concept_name) not like '%allerg%'
	and lower(concept_name) not like '%marker%'
	and lower(concept_name) not like '%alpha%'
	and lower(concept_name) not like '%beta%'
	and lower(concept_name) not like '%igg%'
	and lower(concept_name) not like '%iga%'
	and lower(concept_name) not like '%igm%'
	and lower(concept_name) not like '%igd%'
	and lower(concept_name) not like '%acid%'
	and lower(concept_name) not like '%marker%'
	and lower(concept_name) not like '%synthase%'
	and lower(concept_name) not like '%toxic%'
	and lower(concept_name) not like '%leukotriene%'
	and lower(concept_name) not like '%release%'
	and lower(concept_name) not like '%cd%'
	and lower(concept_name) not like '%curium%'
	and lower(concept_name) not like '%curonium%'
	and lower(concept_name) not like '%carnitine%'
	and lower(concept_name) not like '%smudge%'
	and lower(concept_name) not like '%other%'
	and lower(concept_name) not like '%left%'	
	and lower(concept_name) not like '%megakaryo%'	
	and lower(concept_name) not like '%hairy%'	
	and lower(concept_name) not like '%eosino%'	
	and lower(concept_name) not like '%stain%'
	and lower(concept_name) not like '%hetero%'
	and lower(concept_name) not like '%baso%'
	and lower(concept_name) not like '%fet%'
	and lower(concept_name) not like '%blood product%'
	and lower(concept_name) not like '%malignant%'
	and lower(concept_name) not like '%sezary%'
	and lower(concept_name) not like '%unidentified%'
	and lower(concept_name) not like '%mesothelial%'
	and lower(concept_name) not like '%immature%'
	and lower(concept_name) not like '%low%'
	and lower(concept_name) not like '%bovine%'
	and lower(concept_name) not like '%sulfat%'
	and lower(concept_name) not like '%sodium%'
	and lower(concept_name) not like '%gluc%'
	and lower(concept_name) not like '%galact%'
	and lower(concept_name) not like '%glut%'
	and lower(concept_name) not like '%phosph%'
	and lower(concept_name) not like '%mannose%'
	and lower(concept_name) not like '%dander%'
	and lower(concept_name) not like '%weed%'
	and lower(concept_name) not like '%hla%'
	and lower(concept_name) not like '%yeast%'
	and lower(concept_name) not like '%black%'	
	and lower(concept_name) not like '%complement%'
	and lower(concept_name) not like '%coccine%'
	and lower(concept_name) not like '%food%'	
	and lower(concept_name) not like '%potassium%'
	and lower(concept_name) not like '%magnesium%'
	and lower(concept_name) not like '%latex%'
	and lower(concept_name) not like '%mite%'
	and lower(concept_name) not like '%sialidase%'
	and lower(concept_name) not like '%reductase%'
	and lower(concept_name) not like '%dehydrogenase%'
	and lower(concept_name) not like '%cathepsin%'
	and lower(concept_name) not like '%pattern%'
	and lower(concept_name) not like '%receptor%'	
	and lower(concept_name) not like '%carboxylase%'	
	and lower(concept_name) not like '%oxidase%'	
	and lower(concept_name) not like '%panel%'	
	and lower(concept_name) not like '%beef%'	
	and lower(concept_name) not like '%pork%'	
	and lower(concept_name) not like '%egg%'	
	and lower(concept_name) not like '%deaminase%'
	and lower(concept_name) not like '%bee%'	
	and lower(concept_name) not like '%wasp%'	
	and lower(concept_name) not like '%hornet%'	
	and lower(concept_name) not like '%nut%'	
	and lower(concept_name) not like '%seed%'
	and lower(concept_name) not like '%dog%'
	and lower(concept_name) not like '%flea%'
	and lower(concept_name) not like '%roach%'	
	and lower(concept_name) not like '%pellitory%'	
	and lower(concept_name) not like '%grass%'	
	and lower(concept_name) not like '%indigo%'	
	and lower(concept_name) not like '%lysine%'	
	and lower(concept_name) not like '%wheat%'	
	and lower(concept_name) not like '%soy%'	
	and lower(concept_name) not like '%milk%'	
	and lower(concept_name) not like '%pollen%'	
	and lower(concept_name) not like '%oak%'	
	and lower(concept_name) not like '%albumin%'	
	and lower(concept_name) not like '%peptidase%'	
	and lower(concept_name) not like '%albumin%'	
	and lower(concept_name) not like '%zinc%'	
	and lower(concept_name) not like '%cystin%'	
	and lower(concept_name) not like '%dysferlin%'	
	and lower(concept_name) not like '%cephalosporin%'	
	and lower(concept_name) not like '%celery%'	
	and lower(concept_name) not like '%shrimp%'	
	and lower(concept_name) not like '%oat%'	
	and lower(concept_name) not like '%rye%'	
	and lower(concept_name) not like '%barley%'	
	and lower(concept_name) not like '%crab%'	
	and lower(concept_name) not like '%casein%'
	and lower(concept_name) not like '%cedar%'	
	and lower(concept_name) not like '%xiap%'	
	and lower(concept_name) not like '%perforin%'	
	and lower(concept_name) not like '%ascorbate%'	
	and lower(concept_name) not like '%xiap%'	
	and lower(concept_name) not like 'nucleated%'	
	and lower(concept_name) not like 'erythrocyte%'
	and lower(concept_name) not like '%platelet%'	
	and lower(concept_name) not like '%disintegrated%'	
	and lower(concept_name) not like '%glycyphagus%'	
	and lower(concept_name) not like '%aggregate%'	
	and lower(concept_name) not like '%coenzyme%'	
	and lower(concept_name) not like '%carrot%'	
	and lower(concept_name) not like '%orange%'	
	and lower(concept_name) not like '%tomato%'	
	and lower(concept_name) not like '%fish%'	
	and lower(concept_name) not like '%rfd9%'
	and lower(concept_name) not like '%chloramin%'	
	and lower(concept_name) not like '%tyrophagus%'	
	and lower(concept_name) not like '%birch%'	
	and lower(concept_name) not like '%acarus%'	
	and lower(concept_name) not like '%wort%'	
	and lower(concept_name) not like '%blue%'	
	and lower(concept_name) not like '%cocksfoot%'	
	and lower(concept_name) not like '%meadow%'	
	and lower(concept_name) not like '%plantain%'
	and lower(concept_name) not like '%erythrosine%'	
	and lower(concept_name) not like '%tyrophagus%'	
	and lower(concept_name) not like '%glycophagus%'	
	and lower(concept_name) not like '%dermato%'	
	and lower(concept_name) not like '%timothy%'	
	and lower(concept_name) not like '%minor%'	
	and lower(concept_name) not like '%propyphenazone%'	
	and lower(concept_name) not like '%dipyrone%'	
	and lower(concept_name) not like '%tartrazine%'	
	and lower(concept_name) not like '%chromotrope%'	
	
order by concept_code
;


--SCRATCHWORK
select * from concept where concept_id in (
select descendant_concept_id
from concept_ancestor
where ancestor_concept_id in (4074815, 34000006, 81893)
)
and vocabulary_id = 'SNOMED';

select distinct measurement_concept_name, measurement_concept_id, count(measurement_id)
from measurement_labs
where lower(measurement_concept_name) like '%white blood cell%' or lower(measurement_concept_name) like '%wbc%'
	or lower(measurement_concept_name) like '%leukocyte%'
--	and (lower(measurement_concept_name) like '%serum%'
--		 or lower(measurement_concept_name) like '%plasma%'
--		 or lower(measurement_concept_name) like '%blood%'))
group by measurement_concept_name, measurement_concept_id
order by count(measurement_id) desc

select * from measurement_concept_name where measurement_concept_id in (

	select concept_id from concept
where lower(concept_name) like '%creatinine%'
	and (lower(concept_name) like '%serum%'
		 or lower(concept_name) like '%plasma%'
		 or lower(concept_name) like '%blood%')
	and vocabulary_id in ('LOINC')
and lower(concept_name) not like '%/creatinine%'
and lower(concept_name) not like '%creatinine/%'
and lower(concept_name) not like '%urine%'
and lower(concept_name) not like '%peritoneal%'
and lower(concept_name) not like '%glomerular%'
and lower(concept_name) not like '%ratio%'
and lower(concept_name) not like '%predicted%'
and lower(concept_name) not like '%clearance%'
)